# Generated by Django 5.0.4 on 2024-04-16 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='phone',
        ),
        migrations.AddField(
            model_name='shop',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='media/'),
        ),
    ]
