# Generated by Django 5.0.4 on 2024-04-16 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_shop_phone_shop_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='phone',
            field=models.CharField(default='N/A', max_length=14),
        ),
    ]
