# Generated by Django 5.0.4 on 2024-04-29 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_shop_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='phone',
            field=models.CharField(default='N/A', max_length=10),
        ),
    ]
