# Generated by Django 5.0.4 on 2024-05-02 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_shop_image_alter_shop_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='user',
            field=models.CharField(null=True),
        ),
    ]
