# Generated by Django 5.0.4 on 2024-05-14 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_shop_image_shopimages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopimages',
            name='shop',
        ),
        migrations.AddField(
            model_name='shopimages',
            name='shop',
            field=models.ManyToManyField(to='api.shop'),
        ),
    ]
